# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-12 02:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mata_Kuliah',
            fields=[
                ('id_mk', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nama_mk', models.CharField(max_length=200)),
                ('jumlah_sks', models.IntegerField(max_length=2)),
                ('mk_semester', models.IntegerField(max_length=2)),
            ],
            options={
                'db_table': 'Mata_Kuliah',
            },
        ),
    ]
