# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-12 04:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('identityApp', '0001_initial'),
        ('krsApp', '0002_auto_20151212_1149'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mhs_Ambil_MK',
            fields=[
                ('id_mhs_ambil_mk', models.AutoField(primary_key=True, serialize=False)),
                ('kelas', models.CharField(max_length=1)),
                ('ambil_di_smt', models.IntegerField()),
                ('id_mhs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='identityApp.Mahasiswa')),
                ('id_mk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='krsApp.Mata_Kuliah')),
            ],
            options={
                'db_table': 'Mhs_Ambil_MK',
            },
        ),
    ]
