# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-12 05:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('identityApp', '0001_initial'),
        ('krsApp', '0003_mhs_ambil_mk'),
    ]

    operations = [
        migrations.CreateModel(
            name='KRS',
            fields=[
                ('id_krs', models.AutoField(primary_key=True, serialize=False)),
                ('id_dosen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='identityApp.Dosen')),
                ('id_mhs_ambil_mk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='krsApp.Mhs_Ambil_MK')),
            ],
            options={
                'db_table': 'KRS',
            },
        ),
    ]
