# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-10 17:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Identitas',
            fields=[
                ('id_mhs', models.AutoField(primary_key=True, serialize=False)),
                ('nim', models.CharField(max_length=12, unique=True)),
                ('nama_mhs', models.CharField(max_length=100)),
                ('ttl', models.DateField()),
                ('alamat', models.TextField()),
                ('jenis_kelamin', models.CharField(max_length=10)),
                ('tahun_ajaran', models.CharField(max_length=10)),
                ('id_jurusan', models.CharField(max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Identitas',
            },
        ),
    ]
